//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectRemaxPart2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long RefClient { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long RefEmployee { get; set; }
        public string Type { get; set; }
        public long RefProperty { get; set; }
    }
}
